name:                mlp-hs
version:             0.1.0.0
github:              "ovanr/mlp-hs"
license:             BSD3
author:              "Orpheas van Rooij"
maintainer:          "orpheas.vanrooij@outlook.com"
copyright:           "2021 Orpheas van Rooij"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ovanr/mlp-hs#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- text
- containers
- bytestring
- aeson
- lens-aeson
- hmatrix
- vector
- mtl
- transformers
- filepath
- PyF
- first-class-families
- singletons
- MonadRandom
- constraints

library:
  source-dirs: src

executables:
  mlp-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlp-hs

tests:
  mlp-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlp-hs
